---
  priority: 1
  code: "mini"
  name: "Mini"
  fees: 
    - "mini"
    - "signup"
  campaigns:
    -
      campaignType: "BUNDLE"
      campaignCode: "voice120"
  pricePlanCode: "pp1"
  descriptions:
    monthlyPrice: "29"
    voice: "2 hours"
    data: "2 GB"
    other:
      - "4G"