---
  code: "standard"
  name: "Standard"
  fees: 
    - "standard"
    - "signup"
  pricePlanCode: "pp1"
  descriptions:
    monthlyPrice: "69"
    voice: "6 hours"
    data: "5 GB"
    other:
      - "4G"