---
  code: "pp1"
  name: "Price plan 1"
  trafficPlans: 
    - 
      ratingCode: "voice-home"
      rootLocation: 
        name: "Local call"
        timePlans: 
          - 
            charges: 
              - 
                ratingPlugin: "INITIAL"
                rate: 0.49
              - 
                ratingPlugin: "VOICESTANDARD"
                rate: 0.19
    -
      ratingCode: "voice-int"
      locationPlugin: "BESTMATCH"
      rootLocation:
        name: "International call"
        timePlans:
          -
            charges:
              -
                ratingPlugin: "VOICESTANDARD"
                rate: 1.99
        children:
          -
            subNumber: "373"
            name: "Moldova"
            timePlans:
              -
                charges:
                  -
                    ratingPlugin: "VOICESTANDARD"
                    rate: 0.99